# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: www.e-medicine.cn
    url: https://www.e-medicine.cn/
    maxResponseTime: 60000
    typing: globalping
    location: China
  - name: dlly.e-medicine.cn
    url: http://dlly.e-medicine.cn/
    maxResponseTime: 60000
    typing: globalping
    location: China
  - name: dai-jian
    url: http://113.108.63.190:25565/Scripts/stat-card-height-manager.js
    maxResponseTime: 60000
    typing: globalping
    location: China
  - name: shenfuyou-IPS
    url: https://pda.szfybjy-gzh.com:8085/admin/index.html?v=2024.11.1
    maxResponseTime: 60000
    typing: globalping
    location: China
  - name: shenertong-IPS
    url: http://121.15.136.85:19101/admin/index.html?v=2024.11.1
    maxResponseTime: 60000
    typing: globalping
    location: China


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Live-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 站点状态
  introTitle: "站点在线状态监控"
  introMessage: 站点在线状态监控
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
